SELECT TOP (10) [VendorID]
      ,[trep_pickup_datetime]
      ,[trep_dropoff_datetime]
      ,[passenger_count]
      ,[trip_distance]
      ,[RatecodeID]
      ,[store_and_fwd_flag]
      ,[PULocationID]
      ,[DOLocationID]
      ,[payment_type]
      ,[fare_amount]
      ,[extra]
      ,[mta_tax]
      ,[tip_amount]
      ,[tolls_amount]
      ,[improvement_surcharge]
      ,[total_amount]
      ,[congestion_surcharge]
  FROM [d_trotsenko_schema].[trotsenko_external]